PEN-1374 Shared Infra ALB
whcc/platform-shared-infra pull request #1
Opened 2024-03-25 21:04 UTC by bil-sukhtsooj

# Summary

Create CDK stack that contains shared ALB to be used by our platform app target groups.

# AWS 
We are using L2 construct for creating the ALBs to our specific needs for this shared infra.

Currently we have following resources this stack:

1. ALB (for external apps)
- Two default listeners(`80, 443`) and third listener for port `8081`.
- Security group
     - Outbound: allow all
     - Inbound: allow all
2. ALB (for internal apps) 
- Default two listeners for ports `80, 443`
- Security group
    - Default allow all outbound rule
    - Inbound rule to only allow traffic from ips in the range `10.0.0.0/8`

2024-03-26 20:25 UTC, PatrickNiesen requested changes
Looks great, and I think this will be a good thing to build/update going forward too

2024-03-26 20:25 UTC, PatrickNiesen commented on cdk/package.json
> +        "cdk:proto:prereq": "NODE_ENV=proto cdk deploy platform-prereqstack-proto-ue2 --profile whcc-proto",
Small change I had both **--profile** and **AWS_PROFILE** in here for testing. I would standardize them to one or the other

2024-03-27 16:57 UTC, bil-sukhtsooj commented on cdk/package.json
> +        "cdk:proto:prereq": "NODE_ENV=proto cdk deploy platform-prereqstack-proto-ue2 --profile whcc-proto",
Standardized all of them to use `AWS_PROFILE`

2024-03-27 17:09 UTC, bil-sukhtsooj commented on cdk/lib/constructs/albl2.ts
> +  albExtraListeners?: alb.BaseApplicationListenerProps[],
I agree to renaming with prefix `alb` for consistency.

2024-03-28 20:05 UTC, timturnerwhcc commented on cdk/bin/cdk.ts
> +  environment: process.env.NODE_ENV!
Help me understand why we need this passed all the way through?

2024-03-28 20:22 UTC, troydwhcc commented on cdk/bin/cdk.ts
> +  environment: process.env.NODE_ENV!
There are several layers, and each layer is responsible for part of the naming. We suspect that in the future we may need to support overrides at the top level.
- Naming Convention: `[<global-identifier> "-" ] <component-name> "-" <optional-detail> "-" <aws-identifier> "-" <environment>[ "-" <region>]`
- Component Stack: The stack is responsible for the `component-name`.
- L2 Construct/Module: Owns the `optional-detail`, which is generally only applicable if we have multiple of the same resource type in the same stack.
- L1 Construct/Module: Owns the `was-identifier`. This is the `naming` `resourceEnum`.
- `environment` and `region` should come from the environment configuration (JSON config).

2024-03-28 21:01 UTC, timturnerwhcc commented on cdk/bin/cdk.ts
> +  environment: process.env.NODE_ENV!
This makes sense.

My specific questionwas on `environment: process.env.NODE_ENV!` We don't seem to actually _use_ the `environment` on the `props` in the Stack CDK itself (unless I missed it). The `environment` coming from the `NODE_ENV` defined in `package.json` I could be convinced is a good idea, but it doesn't feel strict enough?

2024-03-29 14:21 UTC, bil-sukhtsooj commented on cdk/bin/cdk.ts
> +  environment: process.env.NODE_ENV!
@timturnerwhcc Good catch! This is unused, I forgot to remove it. I was using `NODE_ENV` in the stack before for condition to create external alb. But then refactored it to use flag from config Json.

2024-03-29 14:56 UTC, troydwhcc commented on cdk/bin/cdk.ts
>    albName: namingConfig.GetAwsNaming("alb"),
I assume that the L3 constructs would not expose this.

2024-04-01 17:10 UTC, bil-sukhtsooj commented
Addressed all the changes we've discussed last Friday.

2024-04-01 20:58 UTC, PatrickNiesen commented on cdk/bin/cdk.ts
>    albName: namingConfig.GetAwsNaming("alb"),
I would think we would want L3 to be the construct that imports the AWSNaming Libraries. Is that what were you thinking? Users of the L3 constructs would need minimum inputs towards naming the components.

2024-04-01 21:27 UTC, troydwhcc commented on cdk/bin/cdk.ts
>    albName: namingConfig.GetAwsNaming("alb"),
I agree with that.

2024-04-01 21:44 UTC, PatrickNiesen approved these changes

2024-04-02 01:48 UTC, andrew-merkouris-whcc commented on cdk/config/default.json
> +      "account": "799497006720",
@bil-sukhtsooj @PatrickNiesen Can we remove default properties which will not get used?

(Same question for all the below properties which are blank)

2024-04-02 01:48 UTC, andrew-merkouris-whcc commented on cdk/config/dev.json
> +      "componentname": "platform",
@bil-sukhtsooj @PatrickNiesen Should we **not** override properties where not necessary?

2024-04-02 13:55 UTC, timturnerwhcc approved these changes
This addresses the concerns I had. I don't feel my approval is sufficient in isolation for merging.

2024-04-02 14:24 UTC, bil-sukhtsooj commented on cdk/config/default.json
> +      "account": "799497006720",
Yes. I cleaned up all unused properties and config file.

2024-04-02 16:25 UTC, andrew-merkouris-whcc approved these changes

2024-04-03 02:46 UTC, merged